name: hex_calculator
description: "Base 16 calculator app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  fluttertoast: ^8.2.12
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  bloc_concurrency: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  test: ^1.26.2

flutter:
  uses-material-design: true
